// frontend/ui/explorer/ExplorerCreateGroupComponent.svelte
<script lang="ts">
    import Check from "@lucide/svelte/icons/check";
    import Plus from "@lucide/svelte/icons/plus";

    import { Button } from "@shadcn/components/ui/button";
    import { Input } from "@shadcn/components/ui/input";

    import * as ctxKeys from "@/core/context";
    import { expandGroup } from "@/core/uiState.svelte";

    const provider = ctxKeys.provider.get();
    const store = ctxKeys.providerData.get();

    let inputMode = $state(false);
    let inputText = $state("");

    function createGroup(name: string) {
        if (!name || name in store.data.groups) return;
        store.data.groups[name] = { items: [] };
        store.data.groupOrder.push(name);
        // Auto-expand newly created group.
        expandGroup(provider.id, name);
    }

    function ok() {
        createGroup(inputText.trim());
        inputText = "";
        inputMode = false;
    }

    function cancel() {
        inputText = "";
        inputMode = false;
    }
</script>

<div class="flex flex-row items-center w-full gap-1">
    {#if inputMode}
        <Input
            bind:value={inputText}
            placeholder="Group name..."
            class="h-8 flex-1 ml-1"
            onkeydown={e => {
                if (e.key === "Enter") ok();
                else if (e.key === "Escape") cancel();
            }}
            onblur={cancel} />
        <!-- onmousedown so the click registers before the Input's onblur. -->
        <Button
            variant="secondary"
            size="icon"
            class="size-8 border cursor-pointer"
            onmousedown={ok}>
            <Check />
        </Button>
    {:else}
        <Button
            variant="secondary"
            class="w-full h-8 border cursor-pointer"
            onclick={() => inputMode = true}>
            <Plus />
            <span>Add Group</span>
        </Button>
    {/if}
</div>

// src/ui/explorer/ExplorerCreateGroupComponent.tsx
import type { ComponentProps, ReactNode } from "react";
import { useState } from "react";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCheck, faPlus } from "@fortawesome/free-solid-svg-icons";

import { Button } from "@shadcn/components/ui/button";
import { Input } from "@shadcn/components/ui/input";

import { useProviderData } from "@/core/context";

/**
 * Button that transforms into an inline input for creating a new group.
 * - Click "Add Group" → shows input + confirm button
 * - Enter or click check → creates group and resets
 * - Escape or blur → cancels and resets
 */
export default function ExplorerCreateGroupComponent() {
    const [providerData, updateProviderData] = useProviderData();
    const [inputMode, setInputMode] = useState(false);
    const [inputText, setInputText] = useState("");

    function createGroup(groupName: string) {
        updateProviderData(draft => {
            if (groupName && !(groupName in providerData.groups)) {
                draft.groups[groupName] = [];
                draft.groupOrder.push(groupName);
                draft.expandedGroups.push(groupName);
            }
        });
    }

    function onOK(e: { preventDefault(): void; }) {
        e.preventDefault();
        createGroup(inputText.trim());
        setInputText("");
        setInputMode(false);
    }

    function onCancel(e: { preventDefault(): void; }) {
        e.preventDefault();
        setInputText("");
        setInputMode(false);
    }

    function ActionButton(props: ComponentProps<"button">) {
        return (
            <Button
                variant="secondary"
                size={"custom" as any}
                className={`border size-8 cursor-pointer ${props.className}`}
                {...props} />);
    }

    return (
        <div className="flex flex-row items-center w-full gap-2 mb-2">
            {inputMode ? <>
                <Input
                    value={inputText}
                    placeholder="Group name..."
                    autoFocus
                    onChange={e => setInputText(e.target.value)}
                    onKeyDown={e => e.key ? onOK(e) : onCancel(e)}
                    onBlur={e => onCancel(e)}
                    className="h-8"/>
                {/* Use onMouseDown to prevent onBlur fired before onClick */}
                <ActionButton className="size-8" onMouseDown={e => onOK(e)}>
                    <FontAwesomeIcon icon={faCheck}/>
                </ActionButton>
            </> : <>
                {/* Use onClick to avoid (what?) */}
                <ActionButton className="w-full" onClick={() => setInputMode(true)}>
                    <FontAwesomeIcon icon={faPlus}/>
                    <span>Add Group</span>
                </ActionButton>
            </>}
        </div>);
}
