// frontend/ui/explorer/ExplorerItem.svelte
<script lang="ts">
    import Ellipsis from "@lucide/svelte/icons/ellipsis";

    import type { Item, ItemVersions } from "@/core/data";

    import { Separator } from "@shadcn/components/ui/separator";
    import * as Collapsible from "@shadcn/components/ui/collapsible";
    import * as Select from "@shadcn/components/ui/select";

    import * as ctxKeys from "@/core/context";
    import { itemExpanded } from "@/core/uiState.svelte";

    import ExplorerItemMenu from "@/ui/explorer/ExplorerItemMenu.svelte";
    import ExplorerPageList from "@/ui/explorer/ExplorerPageList.svelte";

    let { item, itemGroupName }: { item: Item; itemGroupName: string } = $props();

    const provider = ctxKeys.provider.get();
    const expanded = $derived(itemExpanded(provider.id, item.id));
</script>

<Collapsible.Root
    class="flex flex-col p-1 gap-1 rounded-md bg-card border shadow-sm truncate"
    open={expanded.value}
    onOpenChange={v => expanded.value = v}>
    <div class="flex flex-row gap-1">
        <Collapsible.Trigger class="flex-1 pl-1.5 truncate text-left font-mono cursor-pointer">
            {item.name}
        </Collapsible.Trigger>
        {#if item.versions}
            {@const versions: ItemVersions = item.versions}
            <Select.Root type="single" value={versions.current} onValueChange={versions.setCurrentVersion}>
                <Select.Trigger
                    size="sm"
                    class="pl-2 pr-1 py-0 w-24 h-6 rounded-sm shadow-none text-xs text-foreground/60 cursor-pointer">
                    {versions.current}
                </Select.Trigger>
                <Select.Content>
                    {#each versions.recommended as version (version)}
                        <Select.Item value={version} class="text-sm h-7 cursor-pointer">
                            {version}
                        </Select.Item>
                    {/each}
                    <Select.Separator class="m-0.5" />
                    <!-- Placeholder for future full version list popup. -->
                    <Select.Item value="..." disabled class="h-7 px-2 text-sm">
                        <Ellipsis class="mr-1 inline" />
                        <span>More versions</span>
                    </Select.Item>
                </Select.Content>
            </Select.Root>
        {/if}
        <ExplorerItemMenu {item} {itemGroupName} />
    </div>
    <Collapsible.Content class="flex flex-col">
        <Separator />
        <div class="h-1"></div>
        <ExplorerPageList pages={item.pages} />
    </Collapsible.Content>
</Collapsible.Root>

// src/app/ui/explorer/ExplorerItem.tsx
import type { ReadonlyDeep } from "type-fest";

import { Separator } from "@shadcn/components/ui/separator";

import {
    Collapsible,
    CollapsibleTrigger,
    CollapsibleContent,
} from "@radix-ui/react-collapsible";

import {
    Select,
    SelectContent,
    SelectItem,
    SelectSeparator,
    SelectTrigger,
    SelectValue,
} from "@shadcn/components/ui/select";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faEllipsis } from "@fortawesome/free-solid-svg-icons";

import type { Item, ItemVersions } from "@/app/core/data";
import { useProviderUiState } from "@/app/core/context";

import ExplorerItemMenu
    from "@/app/ui/explorer/ExplorerItemMenu";
import ExplorerPageList
    from "@/app/ui/explorer/ExplorerPageList";

export default function ExplorerItem({ item, itemGroupName }: ReadonlyDeep<{
    item: Item,
    itemGroupName: string,
}>) {
    const { expandedItems, updateExpandedItems } = useProviderUiState();

    const expanded = expandedItems.includes(item.id);

    function toggleExpanded() {
        updateExpandedItems(draft => {
            if (expanded) {
                const index = draft.indexOf(item.id);
                if (index !== -1)
                    draft.splice(index, 1);
                else
                    console.warn(`Item "${item.id}" not found in expandedItems`);
            } else {
                draft.push(item.id);
            }
        });
    }

    return (
        <Collapsible
            className="flex flex-col p-1 gap-1 rounded-md bg-accent border shadow-sm truncate"
            open={expanded}
            onOpenChange={toggleExpanded}>
            <div className="flex flex-row gap-1">
                <CollapsibleTrigger asChild className="flex-1 pl-1.5 truncate">
                    <p className="font-mono cursor-pointer">{item.name}</p>
                </CollapsibleTrigger>
                {item.versions &&
                    <ExplorerItemVersionSelector
                        all={item.versions.all}
                        current={item.versions.current}
                        recommended={item.versions.recommended}
                        setCurrentVersion={item.versions?.setCurrentVersion} />
                }
                <ExplorerItemMenu item={item} itemGroupName={itemGroupName} />
            </div>
            <CollapsibleContent className="flex flex-col">
                <Separator />
                <div className="h-1" />
                <ExplorerPageList pages={item.pages} />
            </CollapsibleContent>
        </Collapsible>);
}

function ExplorerItemVersionSelector(props: ReadonlyDeep<ItemVersions>) {
    return (
        <Select value={props.current} onValueChange={props.setCurrentVersion}>
            <SelectTrigger
                // biome-ignore lint/suspicious/noExplicitAny: custom size workaround.
                size={"custom" as any}
                className={
                    "pl-2 pr-1 py-0 w-24 h-6 rounded-sm shadow-none " +
                    "text-xs text-foreground/60 cursor-pointer "}>
                <SelectValue />
            </SelectTrigger>
            <SelectContent>
                {props.recommended.map(
                    version => (
                        <SelectItem
                            key={version}
                            value={version}
                            className="text-sm h-7 cursor-pointer">
                            {version}
                        </SelectItem>
                    ))}
                <SelectSeparator className="m-0.5" />
                {/* Placeholder for future full version list popup */}
                <SelectItem value="..." disabled className="h-7 px-2 text-sm">
                    <FontAwesomeIcon icon={faEllipsis} className="mr-1 inline" />
                    <span>More versions</span>
                </SelectItem>
            </SelectContent>
        </Select>);
}
