// src/app/ui/explorer/ExplorerItemMenu.tsx
import type { ReadonlyDeep } from "type-fest";

import * as _ from "remeda";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
    faArrowUpRightFromSquare,
    faEllipsisVertical,
    faRightToBracket,
} from "@fortawesome/free-solid-svg-icons";

import { Button } from "@shadcn/components/ui/button";
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuSeparator,
    DropdownMenuSub,
    DropdownMenuSubContent,
    DropdownMenuSubTrigger,
    DropdownMenuTrigger,
} from "@shadcn/components/ui/dropdown-menu";

import type { Item, ItemLink, ItemAction, ProviderData } from "@/app/core/data";
import Icon from "@/app/ui/common/Icon";

import { useCurrentUrl, useProviderData } from "@/app/core/context";

export default function ExplorerItemMenu({ item, itemGroupName }: ReadonlyDeep<{
    item: Item,
    itemGroupName: string,
}>) {
    const [providerData, updateProviderData] = useProviderData();
    const moveItemToUngroupedAction = {
        ...getMoveItemAction(
            item.id,
            itemGroupName,
            "",
            updateProviderData),
        name: "Ungrouped",
    };
    const moveItemActions =
        providerData
            .groupOrder
            .filter(targetGroupName => targetGroupName in providerData.groups)
            .map(targetGroupName => (
                getMoveItemAction(
                    item.id,
                    itemGroupName,
                    targetGroupName,
                    updateProviderData)))
    return (
        <DropdownMenu>
            <DropdownMenuTrigger>
                <Button
                    variant="ghost"
                    size="icon"
                    className="size-6 border rounded-sm hover:bg-input/50 cursor-pointer">
                    <FontAwesomeIcon icon={faEllipsisVertical} size="sm" />
                </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent>
                <DropdownMenuSub>
                    <DropdownMenuSubTrigger className="cursor-pointer">
                        <FontAwesomeIcon icon={faRightToBracket} size="sm" />
                        <span>Move to group</span>
                    </DropdownMenuSubTrigger>
                    <DropdownMenuSubContent>
                        <ExplorerItemMenuAction action={moveItemToUngroupedAction} />
                        <DropdownMenuSeparator />
                        {moveItemActions.map(action => (
                            <ExplorerItemMenuAction key={action.name} action={action} />
                        ))}
                    </DropdownMenuSubContent>
                </DropdownMenuSub>
                {item.links && <DropdownMenuSeparator />}
                {item.links?.map(link => (
                    <ExplorerItemMenuLink key={link.url} link={link} />
                ))}
                {item.actions && <DropdownMenuSeparator />}
                {item.actions?.map(action => (
                    <ExplorerItemMenuAction key={action.name} action={action} />
                ))}
            </DropdownMenuContent>
        </DropdownMenu>);
}

function ExplorerItemMenuLink({ link }: ReadonlyDeep<{ link: ItemLink }>) {
    const [_, setCurrentUrl] = useCurrentUrl();
    const defaultLinkIcon = {
        type: "fontawesome",
        name: faArrowUpRightFromSquare,
    } as const;
    return (
        <DropdownMenuItem
            className="cursor-pointer"
            onClick={() => setCurrentUrl(link.url)}>
            <Icon icon={link.icon ?? defaultLinkIcon} size="sm" />
            <span>{link.name}</span>
        </DropdownMenuItem>);
}

function ExplorerItemMenuAction({ action }: ReadonlyDeep<{ action: ItemAction }>) {
    console.log("Rendering action:", action);
    return (
        <DropdownMenuItem
            variant={action.destructive ? "destructive" : undefined}
            disabled={action.disabled}
            className="cursor-pointer"
            onClick={action.invoke}>
            {action.icon && <Icon icon={action.icon} size="sm" />}
            <span>{action.name}</span>
        </DropdownMenuItem>);
}

function getMoveItemAction(
    itemId: string,
    sourceGroupName: string,
    targetGroupName: string,
    updateProviderData: (updater: (draft: ProviderData) => void) => void): ItemAction {
    return {
        name: targetGroupName,
        disabled: targetGroupName === sourceGroupName || undefined,
        invoke(): void {
            if (targetGroupName !== sourceGroupName) {
                updateProviderData(
                    getMoveItemUpdater(
                        itemId,
                        sourceGroupName,
                        targetGroupName));
            }
        },
    };
}

/** Returns an updater function that moves an item from one group to another. */
//* Note that the "ungrouped" group is represented by an empty string as the group name!!
function getMoveItemUpdater(
    itemId: string,
    sourceGroupName: string,
    targetGroupName: string): (draft: ProviderData) => void {
    return draft => {
        // Collect actions to perform after validation to avoid partial updates.
        const actions: (() => void)[] = [];

        if (sourceGroupName) {
            const sourceGroup =
                draft.groups[sourceGroupName];
            if (!sourceGroup) {
                console.warn(
                    `Unable to move item ${itemId}: ` +
                    `Source group "${sourceGroupName}" not found.`);
                return;
            }

            const itemIndex =
                sourceGroup.items.indexOf(itemId);
            if (itemIndex < 0) {
                console.warn(
                    `Unable to move item ${itemId}: ` +
                    `Item not found in source group "${sourceGroupName}".`);
                return;
            }

            actions.push(() => {
                sourceGroup.items.splice(itemIndex, 1);
            });
        }

        if (targetGroupName) {
            const targetGroup =
                draft.groups[targetGroupName];

            if (!targetGroup) {
                console.warn(
                    `Unable to move item ${itemId}: ` +
                    `Target group "${targetGroupName}" not found.`);
                return;
            }

            actions.push(() => {
                targetGroup.items.push(itemId);
                targetGroup.items.sort();
            });
        }

        for (const action of actions) {
            action();
        }
    };
}

// frontend/ui/explorer/ExplorerItemMenu.svelte
<script lang="ts">
    import EllipsisVertical from "@lucide/svelte/icons/ellipsis-vertical";
    import LogIn from "@lucide/svelte/icons/log-in";
    import ExternalLink from "@lucide/svelte/icons/external-link";

    import type { Item, ItemAction, ProviderData } from "@/core/data";
    import * as DropdownMenu from "@shadcn/components/ui/dropdown-menu";
    import Icon from "@/ui/common/Icon.svelte";

    import * as ctxKeys from "@/core/context";

    let { item, itemGroupName }: { item: Item; itemGroupName: string } = $props();

    const navigate = ctxKeys.navigateTo.get();
    const store = ctxKeys.providerData.get();

    /** Build a ItemAction that moves this item from its current group to
     *  the given target group. Used both for the top-level "Ungrouped"
     *  entry and for each named group in the move-to submenu. */
    function buildMoveAction(targetGroupName: string, displayName?: string): ItemAction {
        return {
            name: displayName ?? targetGroupName,
            disabled: targetGroupName === itemGroupName || undefined,
            invoke() {
                if (targetGroupName === itemGroupName) return;
                applyMove(store.data as ProviderData, item.id, itemGroupName, targetGroupName);
            },
        };
    }

    const moveToUngroupedAction = $derived(buildMoveAction("", "Ungrouped"));
    const moveActions = $derived(
        store.data.groupOrder
            .filter(name => name in store.data.groups)
            .map(name => buildMoveAction(name)));

    function applyMove(draft: ProviderData, itemId: string, sourceGroup: string, targetGroup: string) {
        // Mirror the React version's two-phase validate/then-mutate pattern:
        // collect both source-side and target-side mutations, abort on any
        // missing group, then apply all at once. Keeps move operations atomic.
        const ops: (() => void)[] = [];
        if (sourceGroup) {
            const src = draft.groups[sourceGroup];
            if (!src) {
                console.warn(`Move ${itemId}: source group "${sourceGroup}" not found`);
                return;
            }
            const idx = src.items.indexOf(itemId);
            if (idx < 0) {
                console.warn(`Move ${itemId}: not present in source group "${sourceGroup}"`);
                return;
            }
            ops.push(() => src.items.splice(idx, 1));
        }
        if (targetGroup) {
            const tgt = draft.groups[targetGroup];
            if (!tgt) {
                console.warn(`Move ${itemId}: target group "${targetGroup}" not found`);
                return;
            }
            ops.push(() => {
                tgt.items.push(itemId);
                tgt.items.sort();
            });
        }
        for (const op of ops) op();
    }

    /** Default external-link icon (used for `ItemLink` entries that don't
     *  carry their own icon). */
    const defaultLinkIcon = { type: "lucide" as const, icon: ExternalLink };
</script>

<DropdownMenu.Root>
    <DropdownMenu.Trigger
        class="size-6 border rounded-md hover:bg-input/50 cursor-pointer inline-flex items-center justify-center"
        aria-label="Item actions">
        <EllipsisVertical class="size-3.5" />
    </DropdownMenu.Trigger>
    <DropdownMenu.Content>
        <DropdownMenu.Sub>
            <DropdownMenu.SubTrigger>
                <LogIn class="size-3.5" />
                <span>Move to group</span>
            </DropdownMenu.SubTrigger>
            <DropdownMenu.SubContent>
                <DropdownMenu.Item
                    disabled={moveToUngroupedAction.disabled}
                    onSelect={() => moveToUngroupedAction.invoke()}>
                    {moveToUngroupedAction.name}
                </DropdownMenu.Item>
                <DropdownMenu.Separator />
                {#each moveActions as action (action.name)}
                    <DropdownMenu.Item
                        disabled={action.disabled}
                        onSelect={() => action.invoke()}>
                        {action.name}
                    </DropdownMenu.Item>
                {/each}
            </DropdownMenu.SubContent>
        </DropdownMenu.Sub>

        {#if item.links && item.links.length > 0}
            <DropdownMenu.Separator />
            {#each item.links as link (link.name)}
                <DropdownMenu.Item onSelect={() => navigate(link.url)}>
                    <Icon icon={link.icon ?? defaultLinkIcon} size="sm" />
                    <span>{link.name}</span>
                </DropdownMenu.Item>
            {/each}
        {/if}

        {#if item.actions && item.actions.length > 0}
            <DropdownMenu.Separator />
            {#each item.actions as action (action.name)}
                <DropdownMenu.Item
                    variant={action.destructive ? "destructive" : undefined}
                    disabled={action.disabled}
                    onSelect={() => action.invoke()}>
                    {#if action.icon}<Icon icon={action.icon} size="sm" />{/if}
                    <span>{action.name}</span>
                </DropdownMenu.Item>
            {/each}
        {/if}
    </DropdownMenu.Content>
</DropdownMenu.Root>
