// src/ui/explorer/ExplorerGroupHeader.tsx
import type { KeyboardEvent } from "react";
import { useState } from "react";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
    faAnglesDown,
    faAnglesUp,
    faArrowDown,
    faArrowUp,
    faArrowUpFromBracket,
    faChevronDown,
    faChevronRight,
    faCheck,
    faEllipsisVertical,
    faPencil,
    faRightToBracket,
    faTrash,
} from "@fortawesome/free-solid-svg-icons";

import { Button } from "@shadcn/components/ui/button";
import { Input } from "@shadcn/components/ui/input";

import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from "@shadcn/components/ui/dialog";

import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuSeparator,
    DropdownMenuSub,
    DropdownMenuSubContent,
    DropdownMenuSubTrigger,
    DropdownMenuTrigger,
} from "@shadcn/components/ui/dropdown-menu";

import { useProviderData } from "@/core/context";

export default function ExplorerGroupHeader(
    props:
        | { variant: "default", groupName: string }
        | { variant: "ungrouped" }) {
    const groupName = props.variant === "default" ? props.groupName : "";
    const [providerData, updateProviderData] = useProviderData();
    const [DeleteDialog, showDeleteDialog] = useDeleteDialog();
    const [isRenaming, setIsRenaming] = useState(false);
    const [editedName, setEditedName] = useState(groupName);

    if (props.variant === "default") {
        const groupExpanded = providerData.expandedGroups.includes(groupName);
        const isFirstGroup =
            providerData.groupOrder[0] === groupName;
        const isLastGroup =
            providerData.groupOrder[providerData.groupOrder.length - 1] === groupName;

        function toggleGroupExpanded() {
            updateProviderData(draft => {
                if (groupExpanded) {
                    draft.expandedGroups =
                        draft.expandedGroups.filter(name => name !== groupName);
                } else {
                    draft.expandedGroups.push(groupName);
                }
            });
        }

        function expandAll() {
            updateProviderData(draft => {
                const items = draft.groups[groupName]?.items || [];
                for (const itemId of items) {
                    if (!draft.expandedItems.includes(itemId)) {
                        draft.expandedItems.push(itemId);
                    }
                }
            });
        }

        function collapseAll() {
            updateProviderData(draft => {
                const items = draft.groups[groupName]?.items || [];
                draft.expandedItems =
                    draft.expandedItems.filter(id => !items.includes(id));
            });
        }

        function moveToTop() {
            updateProviderData(draft => {
                const filtered = draft.groupOrder.filter(name => name !== groupName);
                draft.groupOrder = [groupName, ...filtered];
            });
        }

        function moveUp() {
            updateProviderData(draft => {
                const thisIndex = draft.groupOrder.indexOf(groupName);
                const prevGroupName = draft.groupOrder[thisIndex - 1];
                if (thisIndex > 0 && prevGroupName !== undefined) {
                    draft.groupOrder[thisIndex - 1] = groupName;
                    draft.groupOrder[thisIndex] = prevGroupName;
                }
            });
        }

        function moveDown() {
            updateProviderData(draft => {
                const thisIndex = draft.groupOrder.indexOf(groupName);
                const nextGroupName = draft.groupOrder[thisIndex + 1];
                if (thisIndex >= 0 && nextGroupName !== undefined) {
                    draft.groupOrder[thisIndex + 1] = groupName;
                    draft.groupOrder[thisIndex] = nextGroupName;
                }
            });
        }

        // Move this group to immediately after the target group
        function moveUnder(targetGroupName: string) {
            updateProviderData(draft => {
                const filtered = draft.groupOrder.filter(name => name !== groupName);
                const targetIndex = filtered.indexOf(targetGroupName);
                if (targetIndex >= 0) {
                    filtered.splice(targetIndex + 1, 0, groupName);
                    draft.groupOrder = filtered;
                }
            });
        }

        function removeGroup() {
            updateProviderData(draft => {
                delete draft.groups[groupName];
            });
        }

        function confirmRename() {
            setIsRenaming(false);
            const trimmed = editedName.trim();
            if (trimmed && trimmed !== groupName) {
                const newName = trimmed;
                updateProviderData(draft => {
                    // Move group data to new name
                    const group = draft.groups[groupName] || { items: [] };
                    delete draft.groups[groupName];
                    draft.groups[newName] = group;

                    // Update groupOrder to use new name
                    const orderIndex = draft.groupOrder.indexOf(groupName);
                    if (orderIndex >= 0) {
                        draft.groupOrder[orderIndex] = newName;
                    }

                    // Preserve expansion state under new name
                    const expandedIndex = draft.expandedGroups.indexOf(groupName);
                    if (expandedIndex >= 0) {
                        draft.expandedGroups[expandedIndex] = newName;
                    }
                });
            }
        }

        function onRenameKeyDown(e: KeyboardEvent) {
            if (e.key === "Enter") {
                confirmRename();
            } else if (e.key === "Escape") {
                setIsRenaming(false);
            }
        }

        // Inline rename input mode
        if (isRenaming) {
            return (
                <div className="flex flex-row items-center h-8 py-0.5">
                    <Input
                        value={editedName}
                        onChange={e => setEditedName(e.target.value)}
                        onKeyDown={onRenameKeyDown}
                        onBlur={confirmRename}
                        autoFocus
                        className="h-7 mx-1 rounded-md font-semibold" />
                    <Button
                        variant="secondary"
                        size="icon"
                        className="size-7 rounded-md"
                        onClick={confirmRename}>
                        <FontAwesomeIcon icon={faCheck} />
                    </Button>
                </div>);
        }

        return (
            <div className="group/header flex flex-row h-8 py-0.5 items-center gap-0.5 text-muted-foreground">
                {/* Group name */}
                <p
                    className="flex flex-row flex-1 gap-2 items-center text-lg pl-1 font-semibold cursor-pointer truncate"
                    onClick={() => toggleGroupExpanded()}>
                    <FontAwesomeIcon
                        icon={groupExpanded ? faChevronDown : faChevronRight}
                        size="sm" />
                    <span className="flex-1 truncate">{groupName}</span>
                </p>
                {/* Rename button*/}
                <Button
                    variant="ghost"
                    size="icon"
                    className="size-7 rounded-md invisible group-hover/header:visible"
                    title="Rename group"
                    onClick={() => {
                        setIsRenaming(true);
                        setEditedName(groupName);
                    }}>
                    <FontAwesomeIcon icon={faPencil} />
                </Button>
                {/* Group Menu */}
                <DropdownMenu>
                    <DropdownMenuTrigger>
                        <Button
                            variant="ghost"
                            size="icon"
                            className="size-7 rounded-md">
                            <FontAwesomeIcon icon={faEllipsisVertical} />
                        </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                        <DropdownMenuItem onClick={expandAll}>
                            <FontAwesomeIcon icon={faAnglesDown} />
                            <span>Expand All</span>
                        </DropdownMenuItem>
                        <DropdownMenuItem onClick={collapseAll}>
                            <FontAwesomeIcon icon={faAnglesUp} />
                            <span>Collapse All</span>
                        </DropdownMenuItem>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem
                            disabled={isFirstGroup}
                            onClick={moveToTop}>
                            <FontAwesomeIcon icon={faArrowUpFromBracket} />
                            <span>Move to Top</span>
                        </DropdownMenuItem>
                        <DropdownMenuItem
                            disabled={isFirstGroup}
                            onClick={moveUp}>
                            <FontAwesomeIcon icon={faArrowUp} />
                            <span>Move Up</span>
                        </DropdownMenuItem>
                        <DropdownMenuItem
                            disabled={isLastGroup}
                            onClick={moveDown}>
                            <FontAwesomeIcon icon={faArrowDown} />
                            <span>Move Down</span>
                        </DropdownMenuItem>
                        {/* "Move Under" submenu - only show if there are other groups */}
                        {providerData.groupOrder.length > 1 && (
                            <DropdownMenuSub>
                                <DropdownMenuSubTrigger className="cursor-pointer">
                                    <FontAwesomeIcon icon={faRightToBracket} />
                                    <span>Move Under</span>
                                </DropdownMenuSubTrigger>
                                <DropdownMenuSubContent>
                                    {providerData
                                        .groupOrder
                                        .filter(name => name in providerData.groups)
                                        .filter(name => name !== groupName)
                                        .map(targetName => (
                                            <DropdownMenuItem
                                                key={targetName}
                                                className="cursor-pointer"
                                                onClick={() => moveUnder(targetName)}>
                                                {targetName}
                                            </DropdownMenuItem>))}
                                </DropdownMenuSubContent>
                            </DropdownMenuSub>)}
                        <DropdownMenuSeparator />
                        <DropdownMenuItem
                            variant="destructive"
                            onClick={showDeleteDialog}>
                            <FontAwesomeIcon icon={faTrash} />
                            <span>Delete Group</span>
                        </DropdownMenuItem>
                    </DropdownMenuContent>
                </DropdownMenu>
                <DeleteDialog
                    title="Delete Group?"
                    callback={removeGroup}>
                    Are you sure you want to delete group "{props.groupName}"?
                    This action cannot be undone.
                </DeleteDialog>
            </div>);
    } else {
        return (
            <div className="group/header flex flex-row h-8 py-0.5 items-center gap-0.5 text-muted-foreground">
                {/* Group name */}
                <p className="flex flex-row flex-1 gap-2 items-center text-lg pl-1 font-semibold cursor-pointer truncate" >
                    <span className="flex-1 truncate">Ungrouped</span>
                </p>
            </div>);
    }
}

function useDeleteDialog() {
    const [open, setOpen] = useState(false);
    return [
        (props: {
            title: string,
            children: undefined | string | string[],
            callback: () => void
        }) => (
            <Dialog open={open} onOpenChange={setOpen}>
                <DialogContent showCloseButton={false}>
                    <DialogHeader>
                        <DialogTitle>{props.title}</DialogTitle>
                        <DialogDescription>{props.children}</DialogDescription>
                    </DialogHeader>
                    <DialogFooter>
                        <Button
                            variant="outline"
                            onClick={() => setOpen(false)}>Cancel</Button>
                        <Button
                            variant="destructive"
                            onClick={() => {
                                props.callback();
                                setOpen(false);
                            }}>Delete</Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>),
        () => setOpen(true),
    ] as const;
}

// frontend/ui/explorer/ExplorerGroupHeader.svelte
<script lang="ts">
    import ChevronsDown from "@lucide/svelte/icons/chevrons-down";
    import ChevronsUp from "@lucide/svelte/icons/chevrons-up";
    import ArrowDown from "@lucide/svelte/icons/arrow-down";
    import ArrowUp from "@lucide/svelte/icons/arrow-up";
    import ArrowUpToLine from "@lucide/svelte/icons/arrow-up-to-line";
    import ChevronDown from "@lucide/svelte/icons/chevron-down";
    import ChevronRight from "@lucide/svelte/icons/chevron-right";
    import Check from "@lucide/svelte/icons/check";
    import EllipsisVertical from "@lucide/svelte/icons/ellipsis-vertical";
    import Pencil from "@lucide/svelte/icons/pencil";
    import LogIn from "@lucide/svelte/icons/log-in";
    import Trash2 from "@lucide/svelte/icons/trash-2";

    import { Button } from "@shadcn/components/ui/button";
    import { Input } from "@shadcn/components/ui/input";
    import * as Dialog from "@shadcn/components/ui/dialog";
    import * as DropdownMenu from "@shadcn/components/ui/dropdown-menu";

    import * as ctxKeys from "@/core/context";
    import { expandItems, collapseItems, removeGroup, renameGroup, groupExpanded } from "@/core/uiState.svelte";

    type Props =
        | { variant: "ungrouped" }
        | { variant: "default"; groupName: string };
    let props: Props = $props();

    const provider = ctxKeys.provider.get();
    const store = ctxKeys.providerData.get();

    // Local UI state for the named-group case. (Always declared at top
    // level so the runes are statically discoverable; no-ops for the
    // "ungrouped" branch.)
    let deleteOpen = $state(false);
    let renaming = $state(false);
    let renameValue = $state("");

    // Reactive expansion accessor; only meaningful for variant="default".
    const expanded = $derived(
        props.variant === "default"
            ? groupExpanded(provider.id, props.variant === "default" ? props.groupName : "")
            : null);

    const isFirst = $derived(
        props.variant === "default"
            ? store.data.groupOrder[0] === props.groupName
            : false);
    const isLast = $derived(
        props.variant === "default"
            ? store.data.groupOrder[store.data.groupOrder.length - 1] === props.groupName
            : false);
    const otherGroups = $derived(
        props.variant === "default"
            ? store.data.groupOrder
                .filter(name => name in store.data.groups)
                .filter(name => name !== props.groupName)
            : []);

    function startRename(currentName: string) {
        renameValue = currentName;
        renaming = true;
    }

    function confirmRename(originalName: string) {
        renaming = false;
        const newName = renameValue.trim();
        if (!newName || newName === originalName) return;
        const group = store.data.groups[originalName] ?? { items: [] };
        delete store.data.groups[originalName];
        store.data.groups[newName] = group;
        const idx = store.data.groupOrder.indexOf(originalName);
        if (idx >= 0) store.data.groupOrder[idx] = newName;
        renameGroup(provider.id, originalName, newName);
    }

    function deleteGroup(groupName: string) {
        delete store.data.groups[groupName];
        store.data.groupOrder = store.data.groupOrder.filter(n => n !== groupName);
        removeGroup(provider.id, groupName);
    }

    function expandAll(groupName: string) {
        expandItems(provider.id, store.data.groups[groupName]?.items ?? []);
    }

    function collapseAll(groupName: string) {
        collapseItems(provider.id, store.data.groups[groupName]?.items ?? []);
    }

    function moveToTop(groupName: string) {
        const filtered = store.data.groupOrder.filter(n => n !== groupName);
        store.data.groupOrder = [groupName, ...filtered];
    }

    function moveUp(groupName: string) {
        const i = store.data.groupOrder.indexOf(groupName);
        const prev = store.data.groupOrder[i - 1];
        if (i > 0 && prev !== undefined) {
            store.data.groupOrder[i - 1] = groupName;
            store.data.groupOrder[i] = prev;
        }
    }

    function moveDown(groupName: string) {
        const i = store.data.groupOrder.indexOf(groupName);
        const next = store.data.groupOrder[i + 1];
        if (i >= 0 && next !== undefined) {
            store.data.groupOrder[i + 1] = groupName;
            store.data.groupOrder[i] = next;
        }
    }

    function moveUnder(sourceName: string, targetName: string) {
        const filtered = store.data.groupOrder.filter(n => n !== sourceName);
        const idx = filtered.indexOf(targetName);
        if (idx < 0) return;
        filtered.splice(idx + 1, 0, sourceName);
        store.data.groupOrder = filtered;
    }
</script>

{#if props.variant === "ungrouped"}
    <div class="group/header flex flex-row h-8 py-0.5 items-center gap-0.5 text-muted-foreground">
        <p class="flex flex-row flex-1 gap-2 items-center text-lg pl-1 font-semibold cursor-pointer truncate">
            <span class="flex-1 truncate">Ungrouped</span>
        </p>
    </div>
{:else if renaming}
    <!-- Inline rename input. Confirms on Enter, cancels on Escape or blur. -->
    <div class="flex flex-row items-center h-8 py-0.5">
        <Input
            bind:value={renameValue}
            class="flex-1 h-7 mx-1 rounded-md font-semibold"
            onkeydown={e => {
                if (e.key === "Enter") confirmRename(props.variant === "default" ? props.groupName : "");
                else if (e.key === "Escape") renaming = false;
            }}
            onblur={() => confirmRename(props.variant === "default" ? props.groupName : "")} />
        <Button
            variant="secondary"
            size="icon-sm"
            class="rounded-md"
            onclick={() => confirmRename(props.variant === "default" ? props.groupName : "")}>
            <Check />
        </Button>
    </div>
{:else}
    {@const groupName = props.groupName}
    <div class="group/header flex flex-row h-8 py-0.5 items-center gap-0.5 text-muted-foreground">
        <p
            class="flex flex-row flex-1 gap-2 items-center text-lg pl-1 font-semibold cursor-pointer truncate"
            onclick={() => expanded && (expanded.value = !expanded.value)}>
            {#if expanded?.value}<ChevronDown size={14} />
            {:else}<ChevronRight size={14} />{/if}
            <span class="flex-1 truncate">{groupName}</span>
        </p>

        <!-- Rename pencil; visible on header hover. -->
        <Button
            variant="ghost"
            size="icon-sm"
            class="rounded-md invisible group-hover/header:visible"
            aria-label="Rename group"
            onclick={() => startRename(groupName)}>
            <Pencil />
        </Button>

        <!-- Group dropdown menu: expand/collapse all, move ops, delete. -->
        <DropdownMenu.Root>
            <DropdownMenu.Trigger
                class="size-7 rounded-md inline-flex items-center justify-center hover:bg-muted hover:text-foreground aria-expanded:bg-muted aria-expanded:text-foreground transition-colors"
                aria-label="Group actions">
                <EllipsisVertical />
            </DropdownMenu.Trigger>
            <DropdownMenu.Content align="end">
                <DropdownMenu.Item onSelect={() => expandAll(groupName)}>
                    <ChevronsDown />
                    <span>Expand All</span>
                </DropdownMenu.Item>
                <DropdownMenu.Item onSelect={() => collapseAll(groupName)}>
                    <ChevronsUp />
                    <span>Collapse All</span>
                </DropdownMenu.Item>
                <DropdownMenu.Separator />
                <DropdownMenu.Item disabled={isFirst} onSelect={() => moveToTop(groupName)}>
                    <ArrowUpToLine />
                    <span>Move to Top</span>
                </DropdownMenu.Item>
                <DropdownMenu.Item disabled={isFirst} onSelect={() => moveUp(groupName)}>
                    <ArrowUp />
                    <span>Move Up</span>
                </DropdownMenu.Item>
                <DropdownMenu.Item disabled={isLast} onSelect={() => moveDown(groupName)}>
                    <ArrowDown />
                    <span>Move Down</span>
                </DropdownMenu.Item>
                {#if store.data.groupOrder.length > 1}
                    <DropdownMenu.Sub>
                        <DropdownMenu.SubTrigger>
                            <LogIn />
                            <span>Move Under</span>
                        </DropdownMenu.SubTrigger>
                        <DropdownMenu.SubContent>
                            {#each otherGroups as targetName (targetName)}
                                <DropdownMenu.Item onSelect={() => moveUnder(groupName, targetName)}>
                                    {targetName}
                                </DropdownMenu.Item>
                            {/each}
                        </DropdownMenu.SubContent>
                    </DropdownMenu.Sub>
                {/if}
                <DropdownMenu.Separator />
                <DropdownMenu.Item variant="destructive" onSelect={() => deleteOpen = true}>
                    <Trash2 />
                    <span>Delete Group</span>
                </DropdownMenu.Item>
            </DropdownMenu.Content>
        </DropdownMenu.Root>
    </div>

    <!-- Delete confirmation. -->
    <Dialog.Root bind:open={deleteOpen}>
        <Dialog.Content>
            <Dialog.Header>
                <Dialog.Title>Delete Group?</Dialog.Title>
                <Dialog.Description>
                    Are you sure you want to delete group "{groupName}"? This action cannot be undone.
                </Dialog.Description>
            </Dialog.Header>
            <Dialog.Footer>
                <Button variant="outline" onclick={() => deleteOpen = false}>Cancel</Button>
                <Button
                    variant="destructive"
                    onclick={() => {
                        deleteGroup(groupName);
                        deleteOpen = false;
                    }}>Delete</Button>
            </Dialog.Footer>
        </Dialog.Content>
    </Dialog.Root>
{/if}
