// frontend/ui/explorer/ExplorerItem.tsx
import type { ReadonlyDeep } from "type-fest";

import {
    Separator,
    Select,
    ListBox,
} from "@heroui/react";

import {
    Collapsible,
    CollapsibleTrigger,
    CollapsibleContent,
} from "@radix-ui/react-collapsible";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faEllipsis } from "@fortawesome/free-solid-svg-icons";

import type { Item, ItemVersions } from "@/core/data";
import { useProvider } from "@/core/context";
import { useItemExpanded } from "@/core/uiState";

import ExplorerItemMenu
    from "@/ui/explorer/ExplorerItemMenu";
import ExplorerPageList
    from "@/ui/explorer/ExplorerPageList";

export default function ExplorerItem({ item, itemGroupName }: ReadonlyDeep<{
    item: Item,
    itemGroupName: string,
}>) {
    const [expanded, setExpanded] = useItemExpanded(useProvider().id, item.id);

    function toggleExpanded() {
        setExpanded(!expanded);
    }

    return (
        <Collapsible
            className="flex flex-col p-1 gap-0.5 rounded-lg bg-accent border shadow-sm truncate"
            open={expanded}
            onOpenChange={toggleExpanded}>
            <div className="flex flex-row gap-1">
                <CollapsibleTrigger asChild className="flex-1 pl-1.5 truncate">
                    <p className="font-mono cursor-pointer">{item.name}</p>
                </CollapsibleTrigger>
                {item.versions &&
                    <ExplorerItemVersionSelector
                        all={item.versions.all}
                        current={item.versions.current}
                        recommended={item.versions.recommended}
                        setCurrentVersion={item.versions?.setCurrentVersion} />
                }
                <ExplorerItemMenu item={item} itemGroupName={itemGroupName} />
            </div>
            <CollapsibleContent className="collapsible-content flex flex-col">
                <Separator className="my-1"/>
                <ExplorerPageList pages={item.pages} />
            </CollapsibleContent>
        </Collapsible>);
}

function ExplorerItemVersionSelector(props: ReadonlyDeep<ItemVersions>) {
    return (
        <Select
            aria-label="Version"
            selectedKey={props.current}
            onSelectionChange={key => props.setCurrentVersion(key as string)}
            className="w-24">
            <Select.Trigger className="h-6 px-2 min-h-0 border bg-transparent shadow-none text-xs text-foreground/60 cursor-pointer">
                <Select.Value />
                <Select.Indicator />
            </Select.Trigger>
            <Select.Popover>
                <ListBox>
                    <ListBox.Section>
                        {props.recommended.map(
                            version => (
                                <ListBox.Item
                                    key={version}
                                    id={version}
                                    textValue={version}
                                    className="text-sm h-7 cursor-pointer">
                                    {version}
                                </ListBox.Item>))}
                    </ListBox.Section>
                    <ListBox.Section>
                        {/* Placeholder for future full version list popup */}
                        <ListBox.Item id="..." textValue="More versions" className="h-7 px-2 text-sm opacity-50">
                            <FontAwesomeIcon icon={faEllipsis} className="mr-1 inline" />
                            <span>More versions</span>
                        </ListBox.Item>
                    </ListBox.Section>
                </ListBox>
            </Select.Popover>
        </Select>);
}

// frontend/src/ui/explorer/ExplorerItem.svelte
<script lang="ts">
    import Ellipsis from "@lucide/svelte/icons/ellipsis";
    import ChevronDown from "@lucide/svelte/icons/chevron-down";
    import ChevronRight from "@lucide/svelte/icons/chevron-right";

    import type { Item, ItemVersions } from "@/core/data";

    import * as Collapsible from "@shadcn/components/ui/collapsible";
    import * as Select from "@shadcn/components/ui/select";

    import * as ctx from "@/core/context.svelte";
    import { itemExpanded } from "@/core/uiState.svelte";

    import ExplorerItemMenu from "@/ui/explorer/ExplorerItemMenu.svelte";
    import ExplorerPageList from "@/ui/explorer/ExplorerPageList.svelte";

    let { item, itemGroupName }: { item: Item; itemGroupName: string } = $props();

    const provider = ctx.getProviderInfo();
    const expanded = $derived(itemExpanded(provider.id, item.id));
</script>

<Collapsible.Root
    class="flex flex-col truncate"
    open={expanded.value}
    onOpenChange={v => expanded.value = v}>
    <div
        class="group/item flex h-7 min-w-0 items-center rounded-sm px-0.5 hover:bg-workbench-hover focus-within:bg-workbench-hover">
        <Collapsible.Trigger
            class="flex h-7 min-w-0 flex-1 items-center gap-1 pl-1.5 text-left font-mono text-[13px]">
            {#if expanded.value}
                <ChevronDown class="size-3.5 shrink-0 text-muted-foreground" />
            {:else}
                <ChevronRight class="size-3.5 shrink-0 text-muted-foreground" />
            {/if}
            <span class="truncate">{item.name}</span>
        </Collapsible.Trigger>
        {#if item.versions}{@render ExplorerItemVersionSelect(item.versions)}{/if}
        <ExplorerItemMenu {item} {itemGroupName} />
    </div>
    <Collapsible.Content class="flex flex-col pl-5">
        <ExplorerPageList pages={item.pages} />
    </Collapsible.Content>
</Collapsible.Root>

{#snippet ExplorerItemVersionSelect(versions: ItemVersions)}
    <Select.Root type="single" value={versions.current} onValueChange={versions.setCurrentVersion}>
        <Select.Trigger
            size="sm"
            class="h-5! w-21 rounded-sm border-transparent bg-transparent py-0 pr-1 pl-1.5 text-[11px] text-muted-foreground shadow-none hover:border-input hover:bg-input/30">
            {versions.current}
        </Select.Trigger>
        <Select.Content>
            {#each versions.recommended as version (version)}
                <Select.Item value={version} class="h-7 px-2 text-xs">
                    {version}
                </Select.Item>
            {/each}
            <Select.Separator class="m-0.5" />
            <!-- Placeholder for future full version list popup. -->
            <Select.Item value="..." disabled class="h-7 px-2 text-xs">
                <Ellipsis class="mr-1 inline" />
                <span>More versions</span>
            </Select.Item>
        </Select.Content>
    </Select.Root>
{/snippet}
